import { db } from "./db";
import { profiles } from "@shared/schema";
import { sql } from "drizzle-orm";

const SEED_PROFILES = [
  {
    userId: "seed-user-1",
    firstName: "Maya",
    age: 28,
    gender: "woman",
    datingPreference: "men",
    location: "San Francisco, CA",
    height: "5'6\"",
    photos: ["/images/profile-1.png", "/images/profile-3.png", "/images/profile-5.png"],
    signals: ["Emotionally Available", "Playful", "Growth Minded"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Communicates Clearly", "Emotionally Consistent", "Kind & Caring"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["The way to my heart is... a spontaneous road trip", "A perfect Sunday looks like... farmers market then cooking together", "I light up when I talk about... design and creativity"],
    questions: ["What's a small thing that makes your day better?", "What does a meaningful relationship look like to you?", "How do you recharge after a long week?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-2",
    firstName: "James",
    age: 31,
    gender: "man",
    datingPreference: "women",
    location: "Oakland, CA",
    height: "6'1\"",
    photos: ["/images/profile-2.png", "/images/profile-4.png"],
    signals: ["Calm Communicator", "Romantic", "Thoughtful"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Keeps Their Word", "Great Listener", "Shows Up Fully"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["I'm proudest of... learning to cook my grandmother's recipes", "Something most people don't know about me... I play jazz piano", "My love language is... quality time"],
    questions: ["What's one thing you're learning right now?", "What kind of conversations do you enjoy most?", "What's a goal you're working toward?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-3",
    firstName: "Priya",
    age: 26,
    gender: "woman",
    datingPreference: "men",
    location: "Berkeley, CA",
    height: "5'4\"",
    photos: ["/images/profile-3.png", "/images/profile-1.png", "/images/profile-5.png"],
    signals: ["Adventurous", "Compassionate", "Witty"],
    datingIntent: "Intentional Dating",
    greenFlags: ["Communicates Clearly", "Genuinely Curious", "Respects Boundaries"],
    connectionStyle: "Ready to Meet Soon",
    conversationStarters: ["A perfect Sunday looks like... hiking with a good podcast", "The way to my heart is... making me laugh until I cry", "I light up when I talk about... travel stories"],
    questions: ["How do you recharge after a long week?", "What's a small thing that makes your day better?", "What kind of conversations do you enjoy most?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-4",
    firstName: "Ethan",
    age: 29,
    gender: "man",
    datingPreference: "women",
    location: "San Jose, CA",
    height: "5'11\"",
    photos: ["/images/profile-4.png", "/images/profile-2.png"],
    signals: ["Affectionate", "Grounded", "Creative"],
    datingIntent: "Open but Serious",
    greenFlags: ["Emotionally Consistent", "Kind & Caring", "Shows Up Fully"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["Something most people don't know about me... I restore vintage furniture", "My love language is... acts of service", "I'm proudest of... building my own business"],
    questions: ["What's one thing you're learning right now?", "What does a meaningful relationship look like to you?", "What's a goal you're working toward?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-5",
    firstName: "Sophie",
    age: 30,
    gender: "woman",
    datingPreference: "everyone",
    location: "Palo Alto, CA",
    height: "5'7\"",
    photos: ["/images/profile-5.png", "/images/profile-1.png", "/images/profile-3.png"],
    signals: ["Romantic", "Thoughtful", "Emotionally Available", "Growth Minded"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Great Listener", "Communicates Clearly", "Keeps Their Word", "Kind & Caring"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["The way to my heart is... thoughtful handwritten notes", "A perfect Sunday looks like... bookshop browsing and cozy cafes", "I light up when I talk about... psychology and human connection"],
    questions: ["What does a meaningful relationship look like to you?", "What's a small thing that makes your day better?", "What's one thing you're learning right now?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-6",
    firstName: "Olivia",
    age: 27,
    gender: "woman",
    datingPreference: "men",
    location: "Portland, OR",
    height: "5'5\"",
    photos: ["/images/profile-1.png", "/images/profile-5.png"],
    signals: ["Playful", "Growth Minded", "Creative"],
    datingIntent: "Intentional Dating",
    greenFlags: ["Genuinely Curious", "Communicates Clearly", "Kind & Caring"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["A perfect Sunday looks like... painting with vinyl playing", "I light up when I talk about... sustainable living"],
    questions: ["What's a goal you're working toward?", "What kind of conversations do you enjoy most?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-7",
    firstName: "Marcus",
    age: 33,
    gender: "man",
    datingPreference: "women",
    location: "Seattle, WA",
    height: "6'0\"",
    photos: ["/images/profile-2.png", "/images/profile-4.png", "/images/profile-1.png"],
    signals: ["Grounded", "Calm Communicator", "Compassionate"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Keeps Their Word", "Emotionally Consistent", "Great Listener"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["The way to my heart is... a home cooked meal and honest conversation", "I'm proudest of... mentoring young people in my community", "My love language is... words of affirmation"],
    questions: ["What does a meaningful relationship look like to you?", "How do you recharge after a long week?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-8",
    firstName: "Ava",
    age: 25,
    gender: "woman",
    datingPreference: "everyone",
    location: "Austin, TX",
    height: "5'3\"",
    photos: ["/images/profile-3.png", "/images/profile-5.png"],
    signals: ["Witty", "Adventurous", "Romantic"],
    datingIntent: "Open but Serious",
    greenFlags: ["Respects Boundaries", "Shows Up Fully", "Communicates Clearly"],
    connectionStyle: "Ready to Meet Soon",
    conversationStarters: ["Something most people don't know about me... I've lived in 4 countries", "The way to my heart is... spontaneous weekend plans"],
    questions: ["What's one thing you're learning right now?", "What's a small thing that makes your day better?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-9",
    firstName: "Daniel",
    age: 30,
    gender: "man",
    datingPreference: "women",
    location: "Denver, CO",
    height: "5'10\"",
    photos: ["/images/profile-4.png", "/images/profile-2.png", "/images/profile-1.png"],
    signals: ["Thoughtful", "Affectionate", "Emotionally Available"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Kind & Caring", "Great Listener", "Keeps Their Word"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["A perfect Sunday looks like... trail running then brunch", "My love language is... physical touch", "I light up when I talk about... space exploration"],
    questions: ["What kind of conversations do you enjoy most?", "What does a meaningful relationship look like to you?", "What's a goal you're working toward?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-10",
    firstName: "Luna",
    age: 24,
    gender: "woman",
    datingPreference: "men",
    location: "Chicago, IL",
    height: "5'8\"",
    photos: ["/images/profile-5.png", "/images/profile-3.png"],
    signals: ["Creative", "Romantic", "Playful"],
    datingIntent: "Intentional Dating",
    greenFlags: ["Genuinely Curious", "Kind & Caring", "Emotionally Consistent"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["I'm proudest of... my poetry collection getting published", "Something most people don't know about me... I do improv comedy"],
    questions: ["How do you recharge after a long week?", "What's a small thing that makes your day better?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-11",
    firstName: "Noah",
    age: 28,
    gender: "man",
    datingPreference: "women",
    location: "Brooklyn, NY",
    height: "5'9\"",
    photos: ["/images/profile-2.png", "/images/profile-4.png"],
    signals: ["Witty", "Growth Minded", "Calm Communicator"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Communicates Clearly", "Shows Up Fully", "Respects Boundaries"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["The way to my heart is... a rooftop sunset and good wine", "A perfect Sunday looks like... record shopping then dim sum"],
    questions: ["What's one thing you're learning right now?", "What's a goal you're working toward?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-12",
    firstName: "Isla",
    age: 29,
    gender: "woman",
    datingPreference: "men",
    location: "Nashville, TN",
    height: "5'6\"",
    photos: ["/images/profile-1.png", "/images/profile-3.png", "/images/profile-5.png"],
    signals: ["Compassionate", "Grounded", "Emotionally Available"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Great Listener", "Keeps Their Word", "Kind & Caring"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["My love language is... quality time over everything", "I light up when I talk about... live music and storytelling", "I'm proudest of... starting my own bakery"],
    questions: ["What does a meaningful relationship look like to you?", "How do you recharge after a long week?", "What kind of conversations do you enjoy most?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-13",
    firstName: "Leo",
    age: 32,
    gender: "man",
    datingPreference: "everyone",
    location: "Los Angeles, CA",
    height: "6'2\"",
    photos: ["/images/profile-4.png", "/images/profile-2.png", "/images/profile-1.png"],
    signals: ["Romantic", "Adventurous", "Affectionate"],
    datingIntent: "Open but Serious",
    greenFlags: ["Shows Up Fully", "Emotionally Consistent", "Communicates Clearly"],
    connectionStyle: "Ready to Meet Soon",
    conversationStarters: ["Something most people don't know about me... I volunteer at an animal shelter", "The way to my heart is... authenticity and laughter"],
    questions: ["What's a small thing that makes your day better?", "What's one thing you're learning right now?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-14",
    firstName: "Zara",
    age: 26,
    gender: "woman",
    datingPreference: "men",
    location: "Miami, FL",
    height: "5'7\"",
    photos: ["/images/profile-5.png", "/images/profile-1.png"],
    signals: ["Playful", "Thoughtful", "Growth Minded"],
    datingIntent: "Intentional Dating",
    greenFlags: ["Respects Boundaries", "Genuinely Curious", "Great Listener"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["A perfect Sunday looks like... yoga then beach with a book", "I light up when I talk about... food from different cultures"],
    questions: ["What's a goal you're working toward?", "What kind of conversations do you enjoy most?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-15",
    firstName: "Caleb",
    age: 27,
    gender: "man",
    datingPreference: "women",
    location: "Minneapolis, MN",
    height: "5'11\"",
    photos: ["/images/profile-2.png", "/images/profile-4.png"],
    signals: ["Calm Communicator", "Compassionate", "Creative"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Kind & Caring", "Emotionally Consistent", "Keeps Their Word"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["I'm proudest of... learning to fly a small plane", "My love language is... acts of service"],
    questions: ["How do you recharge after a long week?", "What does a meaningful relationship look like to you?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-16",
    firstName: "Amara",
    age: 27,
    gender: "woman",
    datingPreference: "men",
    location: "Atlanta, GA",
    height: "5'7\"",
    photos: ["/images/profile-6.png", "/images/profile-10.png", "/images/profile-3.png"],
    signals: ["Emotionally Available", "Growth Minded", "Compassionate"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Communicates Clearly", "Kind & Caring", "Shows Up Fully"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["The way to my heart is... deep conversation over candlelight", "I light up when I talk about... community building and social impact", "A perfect Sunday looks like... brunch with friends then a gallery walk"],
    questions: ["What motivates you to be a better person?", "What does love look like in everyday moments?", "How do you show someone you care?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-17",
    firstName: "Kai",
    age: 29,
    gender: "man",
    datingPreference: "women",
    location: "San Diego, CA",
    height: "5'10\"",
    photos: ["/images/profile-7.png", "/images/profile-9.png", "/images/profile-4.png"],
    signals: ["Adventurous", "Playful", "Grounded"],
    datingIntent: "Intentional Dating",
    greenFlags: ["Genuinely Curious", "Respects Boundaries", "Keeps Their Word"],
    connectionStyle: "Ready to Meet Soon",
    conversationStarters: ["Something most people don't know about me... I surf every morning before work", "A perfect Sunday looks like... beach bonfire with acoustic guitar", "I'm proudest of... traveling to 30 countries solo"],
    questions: ["What adventure would you go on if money wasn't an issue?", "What's your favorite way to spend a lazy afternoon?", "What makes you feel most alive?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-18",
    firstName: "Valentina",
    age: 25,
    gender: "woman",
    datingPreference: "men",
    location: "New York, NY",
    height: "5'4\"",
    photos: ["/images/profile-8.png", "/images/profile-6.png"],
    signals: ["Romantic", "Creative", "Witty"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Great Listener", "Emotionally Consistent", "Kind & Caring"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["My love language is... small surprises that show you were thinking of me", "I light up when I talk about... film photography and indie cinema"],
    questions: ["What's a movie that changed how you see the world?", "What's the kindest thing someone has done for you?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-19",
    firstName: "Rayan",
    age: 31,
    gender: "man",
    datingPreference: "women",
    location: "Washington, DC",
    height: "6'0\"",
    photos: ["/images/profile-9.png", "/images/profile-7.png", "/images/profile-2.png"],
    signals: ["Thoughtful", "Calm Communicator", "Emotionally Available"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Keeps Their Word", "Communicates Clearly", "Shows Up Fully"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["The way to my heart is... genuine curiosity about the world", "I'm proudest of... building a nonprofit for education access", "A perfect Sunday looks like... museum hopping then a quiet dinner"],
    questions: ["What cause do you care most about?", "What does emotional safety mean to you?", "How do you handle conflict in relationships?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-20",
    firstName: "Aisha",
    age: 28,
    gender: "woman",
    datingPreference: "men",
    location: "Philadelphia, PA",
    height: "5'5\"",
    photos: ["/images/profile-10.png", "/images/profile-8.png", "/images/profile-1.png"],
    signals: ["Growth Minded", "Affectionate", "Grounded"],
    datingIntent: "Open but Serious",
    greenFlags: ["Respects Boundaries", "Great Listener", "Emotionally Consistent"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["Something most people don't know about me... I'm training for a marathon", "My love language is... quality time without phones"],
    questions: ["What's a challenge that made you stronger?", "What does your ideal weeknight look like?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-21",
    firstName: "Theo",
    age: 26,
    gender: "man",
    datingPreference: "women",
    location: "Boston, MA",
    height: "5'11\"",
    photos: ["/images/profile-7.png", "/images/profile-4.png"],
    signals: ["Creative", "Romantic", "Witty"],
    datingIntent: "Intentional Dating",
    greenFlags: ["Genuinely Curious", "Kind & Caring", "Communicates Clearly"],
    connectionStyle: "Ready to Meet Soon",
    conversationStarters: ["I light up when I talk about... architecture and the stories buildings tell", "The way to my heart is... someone who can match my sarcasm"],
    questions: ["What's the best date you've ever been on?", "What are you nerdy about?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-22",
    firstName: "Sienna",
    age: 30,
    gender: "woman",
    datingPreference: "everyone",
    location: "Portland, OR",
    height: "5'8\"",
    photos: ["/images/profile-6.png", "/images/profile-3.png", "/images/profile-10.png"],
    signals: ["Compassionate", "Adventurous", "Emotionally Available"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Shows Up Fully", "Great Listener", "Keeps Their Word"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["A perfect Sunday looks like... farmers market then cooking something new", "I'm proudest of... leaving corporate to follow my passion for ceramics", "My love language is... thoughtful gestures"],
    questions: ["What's the bravest thing you've ever done?", "What does being present mean to you?", "How do you nurture your relationships?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-23",
    firstName: "Andre",
    age: 34,
    gender: "man",
    datingPreference: "women",
    location: "Houston, TX",
    height: "6'3\"",
    photos: ["/images/profile-9.png", "/images/profile-2.png"],
    signals: ["Grounded", "Affectionate", "Calm Communicator"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Emotionally Consistent", "Kind & Caring", "Keeps Their Word"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["The way to my heart is... cooking together while music plays", "Something most people don't know about me... I write children's books"],
    questions: ["What's something you'd love to learn together?", "What does home feel like to you?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-24",
    firstName: "Nadia",
    age: 24,
    gender: "woman",
    datingPreference: "men",
    location: "San Francisco, CA",
    height: "5'3\"",
    photos: ["/images/profile-8.png", "/images/profile-1.png", "/images/profile-5.png"],
    signals: ["Playful", "Growth Minded", "Romantic"],
    datingIntent: "Intentional Dating",
    greenFlags: ["Communicates Clearly", "Genuinely Curious", "Respects Boundaries"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["I light up when I talk about... neuroscience and how our brains work", "A perfect Sunday looks like... thrift shopping then trying a new cafe"],
    questions: ["What's a rabbit hole you recently went down?", "What's your comfort movie?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-25",
    firstName: "Miles",
    age: 28,
    gender: "man",
    datingPreference: "everyone",
    location: "Charlotte, NC",
    height: "5'9\"",
    photos: ["/images/profile-7.png", "/images/profile-4.png", "/images/profile-9.png"],
    signals: ["Thoughtful", "Creative", "Emotionally Available"],
    datingIntent: "Open but Serious",
    greenFlags: ["Shows Up Fully", "Great Listener", "Kind & Caring"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["My love language is... remembering the little things you mention", "I'm proudest of... producing my first music album", "Something most people don't know about me... I foster rescue dogs"],
    questions: ["What's a song that always makes you feel something?", "What does vulnerability look like to you?", "What's the best meal you've ever had?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-26",
    firstName: "Jasmine",
    age: 29,
    gender: "woman",
    datingPreference: "men",
    location: "Seattle, WA",
    height: "5'6\"",
    photos: ["/images/profile-10.png", "/images/profile-6.png"],
    signals: ["Calm Communicator", "Thoughtful", "Growth Minded"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Emotionally Consistent", "Communicates Clearly", "Keeps Their Word"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["The way to my heart is... someone who remembers my coffee order", "A perfect Sunday looks like... rainy day with a puzzle and tea"],
    questions: ["What's your relationship with solitude?", "What tradition would you want to start with a partner?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-27",
    firstName: "Xavier",
    age: 30,
    gender: "man",
    datingPreference: "women",
    location: "Phoenix, AZ",
    height: "6'1\"",
    photos: ["/images/profile-9.png", "/images/profile-2.png", "/images/profile-7.png"],
    signals: ["Adventurous", "Romantic", "Grounded"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Respects Boundaries", "Shows Up Fully", "Kind & Caring"],
    connectionStyle: "Ready to Meet Soon",
    conversationStarters: ["I light up when I talk about... stargazing in the desert", "I'm proudest of... teaching my nephew to ride a bike", "My love language is... physical touch and words of affirmation"],
    questions: ["What's the most beautiful place you've ever been?", "What does a perfect evening together look like?", "What are you most grateful for right now?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-28",
    firstName: "Elena",
    age: 26,
    gender: "woman",
    datingPreference: "everyone",
    location: "Denver, CO",
    height: "5'7\"",
    photos: ["/images/profile-8.png", "/images/profile-3.png", "/images/profile-10.png"],
    signals: ["Witty", "Compassionate", "Playful"],
    datingIntent: "Intentional Dating",
    greenFlags: ["Genuinely Curious", "Great Listener", "Emotionally Consistent"],
    connectionStyle: "Steady with Momentum",
    conversationStarters: ["Something most people don't know about me... I do stand-up comedy on open mic nights", "The way to my heart is... making me laugh so hard I snort"],
    questions: ["What's the funniest thing that happened to you this week?", "What makes a good conversation partner?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-29",
    firstName: "Omar",
    age: 33,
    gender: "man",
    datingPreference: "women",
    location: "Chicago, IL",
    height: "5'10\"",
    photos: ["/images/profile-7.png", "/images/profile-9.png"],
    signals: ["Emotionally Available", "Affectionate", "Thoughtful"],
    datingIntent: "Meaningful Relationship",
    greenFlags: ["Keeps Their Word", "Kind & Caring", "Communicates Clearly"],
    connectionStyle: "Slow & Intentional",
    conversationStarters: ["I'm proudest of... my garden that feeds the whole neighborhood", "My love language is... cooking your favorite meal after a hard day"],
    questions: ["What does partnership mean to you?", "What's a lesson love has taught you?"],
    onboardingComplete: true,
  },
  {
    userId: "seed-user-30",
    firstName: "Mila",
    age: 25,
    gender: "woman",
    datingPreference: "men",
    location: "Los Angeles, CA",
    height: "5'5\"",
    photos: ["/images/profile-6.png", "/images/profile-8.png", "/images/profile-1.png"],
    signals: ["Romantic", "Creative", "Adventurous"],
    datingIntent: "Open but Serious",
    greenFlags: ["Shows Up Fully", "Respects Boundaries", "Genuinely Curious"],
    connectionStyle: "Ready to Meet Soon",
    conversationStarters: ["A perfect Sunday looks like... sunrise hike then fresh juice", "I light up when I talk about... dance and movement as self-expression", "The way to my heart is... planning a surprise adventure"],
    questions: ["What's an experience on your bucket list?", "What does freedom mean in a relationship?", "What's the most spontaneous thing you've ever done?"],
    onboardingComplete: true,
  },
];

export async function seedDatabase() {
  try {
    const existing = await db.select({ count: sql<number>`count(*)::int` }).from(profiles);
    if (existing[0].count > 0) {
      console.log("Database already has profiles, skipping seed");
      return;
    }

    for (const profile of SEED_PROFILES) {
      await db.insert(profiles).values(profile);
    }

    console.log(`Seeded ${SEED_PROFILES.length} profiles`);
  } catch (error) {
    console.error("Error seeding database:", error);
  }
}
