ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS call_connected_at TIMESTAMPTZ;

ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS call_is_paid BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS call_media_type TEXT NOT NULL DEFAULT 'phone',
  ADD COLUMN IF NOT EXISTS call_payer_id TEXT;

ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS last_call_session_id TEXT,
  ADD COLUMN IF NOT EXISTS last_call_counted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS last_call_stage INTEGER,
  ADD COLUMN IF NOT EXISTS last_call_is_paid BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS last_call_media_type TEXT,
  ADD COLUMN IF NOT EXISTS last_call_payer_id TEXT;